server:
  port: 8080

spring:
  devtools:
    restart:
      exclude: application.yaml
  datasource:
    url: jdbc:mysql://172.26.230.217:3306/hive
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源其他配置(需要使用单独的配置类来进行注入)
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


yamltest:
  str: 字符串不需要加双引号
  num: 666
  floatnum: 0.5
  birth: 2020/10/10 21:12:21
